[tool.pytest.ini_options]
addopts = "-v -s"
testpaths = [
    "tests"
]
python_files = [
    "test_*.py"
]

[tool.coverage.run]
source = ["agentflow"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "if __name__ == .__main__.:",
    "raise NotImplementedError",
    "pass"
]

[tool.black]
line-length = 88
target-version = ['py311']

[tool.isort]
profile = "black"
multi_line_output = 3
