# Default Agent Configuration
name: default_agent
type: generic
capabilities:
  - reasoning
  - analysis
  - task_decomposition

optimization:
  strategy: adaptive
  learning_rate: 0.01
  exploration_rate: 0.1

instruction_set:
  - base_reasoning
  - context_understanding
  - task_planning

performance_metrics:
  accuracy_threshold: 0.85
  efficiency_threshold: 0.75

error_handling:
  retry_strategy: exponential_backoff
  max_error_tolerance: 3
